export interface Theme {
    name: string
    key: string
    background: string
    trackBg: string
    text: string
    textSecondary: string
    mutedText: string
    fontFamily: string
    nodeColors: Record<string, string>
    modeColors: Record<string, string>
    sidebarBg: string
    sidebarBorder: string
    sidebarText: string
    sidebarTextActive: string
    sidebarHover: string
    border: string
    borderLight: string
    inputBg: string
    inputBorder: string
    buttonBg: string
    buttonHover: string
    buttonText: string
    modalBg: string
    modalBorder: string
    contextBg: string
    contextBorder: string
    contextHover: string
    scrollbarTrack: string
    scrollbarThumb: string
    scrollbarThumbHover: string
    dangerText: string
    dangerHover: string
    accentText: string
    accentHover: string
    stayField: string
    wrapIndicator: string
    segmentLabel: string
    divider: string
    blockBorder: string
    blockCompactBorder: string
    blockCompactBg: string
    diagramItemBorder: string
    badgeText: string
    fallbackTrack: string
    starRarity5: string
    starRarity4: string
    starRoverGradient: string
    overlayBackdrop: string
    avatarText: string
    dragOverBg: string
    selectedModeBg: string
    selectedModeRing: string
    deleteBtnBorder: string
    deleteBtnHover: string
    alertBtnBg: string
    confirmBtnBg: string
    exportBg: string
    panelBg: string
    ringOffset: string
    keyIconPath: string
    comboBg: string
    comboBorder: string
    comboText: string
}
